# -------
# Library
# -------

library:
  name: ComposeColors
  api: 21
  github: MFlisar/ComposeColors
  maven: io.github.mflisar.composecolors
  maven-main-library: core
  multiplatform: true
  screenshots:
    - name: Palettes
      images:
        - ./screenshots/material.png
        - ./screenshots/x11.png
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.0
    compose: 1.7.0
    material3: 1.3.0
    experimantal: false

# -------------
# Module
# -------------

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: core 
  - name: modules
    label: Modules
    gradle-comment: modules

modules:
  - name: core
    group: core
    description: the core module - is always automatically included by any module
    optional: false
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: material
    group: modules
    description: defines all material colors
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: x11
    group: modules
    description: defines all x11 colors
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []  
  - name: material-palette
    group: modules
    description: defines a palette and groups for the material colors
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: x11
    group: modules
    description: defines a palette for the x11 colors
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []