# -------
# Library
# -------

library:
  name: ComposeColors
  api: 21
  github: MFlisar/ComposeColors
  maven: io.github.mflisar.composecolors
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - macos
    - ios
    - js
    - wasm
  screenshots: 
    - name: material
      images:
        - ./screenshots/material/material.png
    - name: x11
      images:
        - ./screenshots/x11/x11.png
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.0 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.1 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.0 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: Modules

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic classes
    optional: false
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: material
    group: modules
    description: provides constants for all material colors
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: material-palette
    group: modules
    description: provides a palette class for all material colors
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: x11
    group: modules
    description: provides constants for all X11 colors
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: x11-palette
    group: modules
    description: provides a palette class for all X11 colors
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []